
== Terms and Definitions
This document uses the terms defined in Sub-clause 5.3 of [OGC 06-121r9], which is based on the ISO/IEC Directives, Part 2, Rules for the structure and drafting of International Standards. In particular, the word "`shall`" (not "`must`") is the verb form used to indicate a requirement to be strictly followed to conform to this standard.

For the purposes of this document, the following additional terms and definitions apply.


=== dataset

collection of data, published or curated by a single agent, and available for access or download in one or more formats

[.source]
<<dcat>>

NOTE: The use of 'collection' in the definition from <<dcat,[DCAT]>> is broader than the use of the term collection in this specification.

=== distribution

represents an accessible form of a *dataset*

[.source]
<<dcat>>

[example]
a downloadable file, an RSS feed or an API.

=== feature
alt:[characteristic]
deprecated:[character]

abstraction of real world phenomena

[.source]
<<iso19101,ISO 19101-1:2014>>, added alternative term for "`characteristic`" and deprecated term "`character`".

NOTE: For those unfamiliar with the term 'feature', the explanations on https://www.w3.org/TR/sdw-bp/#spatial-things-features-and-geometry[Spatial Things, Features and Geometry] in the W3C/OGC Spatial Data on the Web Best Practice document provide more detail.

[[subsec-process]]
=== Process

A *process* p is a function that for each input returns a corresponding output

[%unnumbered]
[stem]
++++
mu: X -> Y
++++

where stem:[X] denotes the domain of arguments x and stem:[Y] denotes the co-domain of values y. Within this specification, process arguments are referred to as process inputs and result values are referred to as process outputs. Processes that have no process inputs represent value generators that deliver constant or random process outputs.


=== Process description

A process description is an information model that specifies the interface of a process. A process description is used for a machine-readable description of the process itself but also provides some basic information about the process inputs and outputs.

////
=== Process input:
Process inputs are the arguments of a process and refer to data provided to a process. Each process input is an identifiable item.

=== Process output:
Process outputs are the results of a process and refer to data returned by a process. Each process output is an identifiable item.

=== Process profile:
A process profile is a description of a process on an interface level. Process profiles may have different levels of abstraction and cover several aspects. On a generic level, a process profile may only refer to the provided functionality of a process, i.e. by giving a verbal or formal definition how the outputs are derived from the inputs. On a concrete level a process profile may completely define inputs and outputs including data type definitions and formats.

=== WPS Server:
A WPS Server is a web server that provides access to simple or complex computational processing services.

=== Process offering:
A process offering is an identifiable process that may be executed on a particular service instance. A process offering contains a process description as well as service-specific information about the supported execution protocols (e.g. synchronous and asynchronous execution).

=== Process execution:
The execution of a process is an action that calculates the outputs of a given process for a given set of data inputs.

=== Job:
The (processing) job is a server-side object created by a processing service for a particular process execution. A job may be latent in the case of synchronous execution or explicit in the case of asynchronous execution. Since the client has only oblique access to a processing job, a Job ID is used to monitor and control a job.

=== Service profiles for WPS:
A service profile for WPS is a conformance class that defines the general capabilities of a WPS server, by (1) specifying the supported service operations, (2) the process model, (3) the supported process execution modes, (4) the supported operation binding(s).

////
