
== Revisions to Volume 1: CDB Core Model and Physical Data Store

=== Introductory Clause "`Future Work`"
Updated to reflect work done in CDB version 1.1 as well as new requirements identified in OGC Testbed 13.

=== 1.0.1 Corrigendum changes included
All CDB 1.0.1 Corrigendum changes incorporated. See OGC document 17-064 Summary of Corrigendum Changes for CDB Volume1: Core.

=== General Change: All file extensions in Requirements are now generic
All file specific extensions stated in requirements have been made generic. For example, CDB Volume 1 Requirement formerly stated:

The files from the GSModelGeometry and GSModelInteriorGeometry datasets SHALL have the following naming convention: `LatLon_Dnnn_Snnn_Tnnn_LOD_Un_Rn_FeatureCode_FSC_MODL.flt`.

This Requirement now reads:

The files from the GSModelGeometry and GSModelInteriorGeometry datasets SHALL have the following naming convention: `LatLon_Dnnn_Snnn_Tnnn_LOD_Un_Rn_FeatureCode_FSC_MODL.<ext>`

Where `<ext>` is the correct file name extension for the data encoded in the file. There is also a footnote that specifies what the extension was in version 1.0 of the CDB standard.

=== Clause 1.4.3 CDB Metadata
This clause was updated to:

- Provide definitions for metadata, controlled vocabularies, and enumerations. These are in clauses 1.4.3.1, 1.4.3.2, and 1.4.3.3.
- Insert a table that provides more detailed information on each of the files included in the metadata folder.

=== Clause 1.4.4 CDB Directory File Naming and Structure
This clause is updated to:

- Reflect the use of generic file extensions in all Requirements and the Abstract Test Suite rather than specific file extensions.
- Reflect the addition of enumerations and controlled vocabularies as concepts in the standard.

=== Clause 1.7.1.4 System Hardware Independence
Slight re-wording to make the sentence grammatically correct.

=== Clause 3.1.1 Metadata Directory
Reformatted to be more easily read and understood.

=== Clause 3.1.1Metadata Directory
A new metadata file description for global metadata – including geospatial metadata -applicable to an entire CDB data store was added. This new metadata file description needs to be read in concert with the changes in clauses 1.4.3, 5.1, and specifically 5.1.6.

=== Clause 3.4.2.4 Examples
An example of the file path for all associated metadata is included.

=== Clause 3.4.4.3 Examples
An example of the file path for all associated metadata is included.

=== Clause 3.4.4.4 Examples
An example of the file path for all associated metadata is included.

=== Clause 3.4.5.2 Examples
An example of the file path for associated metadata is included.

=== Clause 5.1 enhanced to include discussion of Controlled Vocabularies
Clause 5.1 has additional wording explaining CDB use of metadata, enumerations and controlled vocabularies. This change resulted from the work in CDB 1.1 for metadata. Many elements in CDB 1.0 that were referred to as metadata are actually enumerations and controlled vocabularies.

=== Clause 5.1.1 Global Metadata
A new clause added that defines what is meant by Global Metadata in general for a CDB data store.

=== Clause 5.1.2 Local Metadata
A new clause added that defines what is meant by Local Metadata for a CDB data store.

=== Clause 5.1.8 (Formerly Clause 5.1.6) Version Metadata
Specification version definition enhanced to include both OGC and community versions of the standard.

Addition of a mandatory `<Metadata standard="metadata-standard-name">` element that specifies the metadata standard used for a CDB data store. This includes a list of metadata standards commonly used in the geospatial and simulation industries. This enumeration is governed by and agreed to by the OGC CDB Standards Working Group. Other metadata standards or profiles of standards may be added upon request and with proper justification. For backwards compatibility, the Metadata_standard element can be set to "`NoMetadata`".

=== Clause 5.1.12 Geospatial Metadata Guidance
This is a new clause that provides general implementation guidance for encoding and storing metadata in a CDB data store.

=== Clause 5.1.12.1 Suggested Global Geospatial Metadata Elements
This is a new clause that provides guidance on which metadata elements should be included in the global metadata resource.

=== Clause 5.1.12.2 Suggested Local Geospatial Metadata Elements
This is a new clause that provides guidance on which metadata elements should be included in a local metadata resource.

=== Clause 5.6
Cross walked the CDB tiled grid concept with the OGC/ISO baseline, specifically the OGC Coverage Implementation Schema (CIS) September 2017.

=== Clause 5.6.2.3.2 VSTI Default Read Value (Change Request 490)
Requirement 102 is against CDB client-devices and not the CDB data store itself. This is an untestable requirement, and further, a client-device should be allowed to read and consume a CDB in any manne that it wishes. There might well be good reasons to not follow those rules in a client-device, so the spec should not impose this.

Therefore, this requirement was removed and replaced with informative guidance for client implementations. The related test 102 is removed from Annex A - Abstract Test Suite.

=== New Clause: 5.7.1.6.4 Network Vector Priority
After CDB was submitted to the OGC, the CDB user community added a new sub-clause to clarify rules for network vector priority. This CDB user community approved clause is now incorporated in Volume 1 of the OGC CDB standard, version 1.1.

=== New Clause: 5.7.1.9 Vector Significant Size and Spatial Significance Criteria
After CDB was submitted to the OGC, the CDB user community added a new sub-clause to clarify rules for vector significant size and spatial significance. This CDB user community approved clause is now incorporated in Volume 1 of the OGC CDB standard, version 1.1. Clause 5.7.1.9 includes two sub-clauses: 5.7.1.9.1 Vector Significant Size and 5.7.1.9.2 Levels of Detail and Spatial Significance Criteria.

=== Annex A: Abstract Test Suite
All tests that had specific file extensions, such as .shp or .flt, are now generic with a note as to what the extensions were in version of the CDB standard prior to version 1.1.


=== Table 5-1 Component Selectors for CDB Controlled Vocabularies and Metadata
A new selector value "`12`" for global metadata was added.

=== Table 5-9: Component Selectors for GTModel Datasets
Provide correct volume and section reference to GTModel descriptor definition. Please note, while this descriptor content is called metadata, this IS NOT the metadata as defined in Volume 1 clauses 5.1.1 and 5.1.2.

=== Figure 5-25. Two instances of code 65
After verification with the reference document, the correct lines are:

- `64`: Gable with Monitor
- `65`: Reserved

The reference document is Digest Part 4, ISO 15046-10 Profile, March 1999, Annex B, Attribute and Value Codes.

=== Table 5-27 Use of "`D`" has two meanings. (Change Request 471)
There was recommendation to remove the use of "D" indicating a "Deprecated Attribution Schema" and keep just one use of "D" for "Dependent on another attribute". This recommendation was accepted and the change made to Table 5-27.

=== Table 5-27 not entirely visible (Change Request 481)
In version 1.0, Table 27 is not entirely visible (clipped at page edge). This comment was accepted and the change made to the table prior to insertion into Volume 1 Core.

=== CDB_Attributes.xml Schema error (Change Request 482)
In: `CDB_Attributes.xml`

[%unnumbered]
[source,xml]
----
No.:9
Attr short name:BOTY
Attr name: Boundary Type
Description: "...See table 5-29 for a list of accepted values..."
----

The table 5-29 was corrected to be 5-19.
