
== The Enterprise View of OGC

=== Interoperability Is Essential

Standards are the basis for the success of the Internet and the World Wide Web. The Net has reshaped how we view and share information. Standards are a fundamental enabling technology of the Net. Standards allow thousands of applications, vendor solutions, and technologies to be *interoperable*. The Net, via standards, is vendor and content-neutral. A standard describes requirements and recommendations that have been agreed to in a consensus forum, such as the Internet Engineering Task Force (IETF), the International Organization for Standardization (ISO), or the OGC. To be useful, standards should represent the "best engineering practices" providing technical value, both in enhancement of individual products, and the multiplicative factor of providing inter-application operability, communication and cooperation.

As described in http://portal.opengeospatial.org/files/?artifact_id=6211&version=2&format=pdf[The Importance of Going Open] White Paper, non-interoperability impedes the sharing of data and the sharing of computing resources, causing organizations to spend much more than necessary on geospatial information technology development. At its best, the Web works in a near frictionless environment, allowing data and processes to flow and interact with a minimal number of barriers. Standards tear down barriers and obstacles to the flow of information and services – they make the Web as we know it possible. OGC plays the particular role of making spatial information open and seamless on the Web.

http://portal.opengeospatial.org/files/?artifact_id=5097&version=3&format=pdf[The Havoc of Non-Interoperability] White Paper identifies risks associated with non-interoperability. Today, lives and property depend on digital information flowing smoothly from one information system to another. Public safety, disaster management, and military applications increasingly depend on communication between dissimilar systems. No single organization produces all the data (so it's inconsistent) and no single vendor provides all the systems (so the systems use different system architectures, which are usually based on different proprietary interfaces).

Organizations like the OGC, the IETF, the World Wide Web Consortium (W3C) and others are open organizations in the sense that any individual or organization can participate, the topics of debate are largely public, decisions are democratic (usually by consensus), and specifications are free and readily available. An “open” process is necessary to arrive at an “open” standard. The openness that OGC promotes is part of this general progress.

Often the terms “open standards” and “open source” are confused or incorrectly taken to mean the same thing. The OGC standards are specifications developed in an open process. Open source is software made freely available under a license that allows the program to run for any purpose, to study how the program works, to adapt it, and to redistribute copies, including modifications. As a matter of policy, the OGC Board of Directors and staff don't favor either proprietary software or open source software. From the OGC perspective, any developer who implements OGC standards in software or online services is doing the right thing. OGC cares about interoperability – the ability to share geospatial information.

=== An Example: Web Map Service

OGC’s http://www.opengeospatial.org/standards/wms[Web Map Service standard] is an example of interoperability achieved through open standards. It is of particular importance since the "map" is a potent user interface tool for conveying spatial information in a compact, useful and meaningful form. The Web Map Service standard began as discussion in the OGC Specification Program that became the first OGC Interoperability Program initiative, the Web Mapping Testbed, in 1998. The WMS candidate interface standard that was developed in the WMS Testbed was adopted as an OpenGIS Implementation Specification in 2000 (WMS version 1.0). Since then, WMS has progressed in maturity with implementations numbering in the thousands. WMS is now also published as ISO 19128.

WMS provides a simple example of how topics are discussed in this reference model:

* Section 2.3 <<spatial_referencing,Spatial Referencing>> describes coordinate reference systems (CRSs) used in WMS. CRSs are vital to geospatial interoperability;

* Section 3.2 <<ogc_web_services,OGC Web Services>> describes several OGC geospatial web services, including WMS, as a coordinated service architecture implemented with common elements across services;

* Section 4.4 <<spatial_data_infrastructures,Spatial Data Infrastructures>> describes the use of WMS and other OGC Web Services in a reusable pattern for deployment for worldwide SDIs.

* Section 5.1 <<ogc_compliance_test_program,OGC Compliance Test Program>> describes the automated testing resources available for all approved OGC services; these resources allow implementers to determine compliance with the OGC specifications.

WMS has dramatically increased the use of on-line mapping. One issue of http://ogcuser.opengeospatial.org/epublish/3/v0n4[OGC User] describes the use of the WMS standard in helping with disaster response to hurricane Katrina, soils data distribution in Europe, a statewide data center, and access via mobile phones. In another http://ogcuser.opengeospatial.org/epublish/4[OGC User] article, the number of WMS servers on the Internet is seen to rise each week as more organizations realize the power of using open standards. At the same time, the number of WMS clients – designed for use in a browser, or on the desktop or on a mobile device – is growing.

=== Business Processes Benefit from Geospatial Standards

http://portal.opengeospatial.org/files/?artifact_id=5098&version=2&format=pdf[Integrating Geospatial Standards and Standards Strategies into Business Process] – an OGC White Paper – identified many business processes that could benefit from the integration of geospatial information and services currently do not. This is because geospatial information has been locked in non-standard systems using different information models and storage structures – often referred to as “stove pipes.” A commitment to interoperability and to implementing open standards unlocks this foundational information type...

For over a decade, the OGC has been promoting the benefits of open geoprocessing specifications. In the last several years, we have seen an increase in the number of policy statements regarding the use of OGC standards. The federal and national agencies involved are endorsing OGC standards. OGC members and users of OGC standards offer testimonials in an http://www.opengeospatial.org/ogc/quotes[endorsements] section of OGC website.

Several studies document the benefits of developing and implementing standards. Examples of such studies include: "The Economic Benefits of Standardization," published by the DIN German Institute for Standardization, e. V. Beuth Verlag, in April, 2000; "The Value of Standards: A Delphi Study" published in June, 2003; http://gio.gsfc.nasa.gov/docs/ROI%20Study.pdf["Geospatial Interoperability Return on Investment Study,"] prepared by Booz Allen Hamilton, Inc. for the National Aeronautics and Space Administration (NASA) in April 2005; and http://inspire.jrc.ec.europa.eu/reports/Study_reports/catalonia_impact_study_report.pdf[the Socio-Economic Impact of the Spatial Data Infrastructure of Catalonia] by the European Commission in 2008. These reports document in ROI terms the value that accrues for users, technology providers, and society when open standards are used. The enterprise "return on investment" in open interfaces is unquestionable today.

=== The OGC Programs

The OGC is an international industry consortium of companies, government agencies and universities participating in a consensus process to develop publicly available interface standards. The OGC is organized into four operational business areas.

* In the http://www.opengeospatial.org/ogc/programs/spec[OGC Standards Program], the OGC Technical Committee and OGC Planning Committee work in a formal consensus process to create and revise member-adopted OpenGIS Standards.

* The http://www.opengeospatial.org/ogc/programs/ip[OGC Interoperability Program] is a series of engineering initiatives to accelerate the development and acceptance of OGC Standards and that OGC technology meets user environments and needs.

* The http://www.opengeospatial.org/ogc/programs/ocap[OGC Marketing and Communication Program] leads outreach and education efforts; nurtures strategic partnerships and alliances; and develops and supports regional and sector programs.

* The http://www.opengeospatial.org/compliance[OGC Compliance Program] provides a process whereby compliance can be tested and certified - indicating that compliance with OGC Implementation Specifications has been achieved.

http://www.opengeospatial.org/ogc/policies[Policies and Procedures] guide the work of the OGC programs. These policies assure the openness of the OGC process, outlining how change requests and dissents are to be treated and adjudicated so the all technically legitimate issues are treated fairly, without prejudice and in a timely manner. OGC Policies also standardized quality control mechanisms to assure structure and relevance of OGC standards to their avowed purpose.

=== OGC Standards and Other Documents

The OGC technical documents have been developed by the membership to address specific interoperability challenges and opportunities. http://www.opengeospatial.org/standards[OGC documents] are available to everyone at no cost.

OGC publishes several different types of documents (<<table1>>). Sections 2 and 3 of the ORM contain exclusively Standards, Abstract Specifications and to a lesser extent Best Practices. Other ORM sections may include other OGC Document Types.

[[table1]]
.OGC Document Types
|===
h| OGC Document Type h| Description
| OpenGIS Implementation Standard | A document containing an OGC consensus, technology dependent standard for application programming interfaces and related standards based on the Abstract Specification or domain-specific extensions to the Abstract Specification. There are five subtypes: Interface, Encoding, Profile, Application Profile, and Application Schema.
| Abstract Specification | A document (or set of documents) containing an OGC consensus, technology-independent standard for application programming interfaces and related standards based on object-oriented or other IT accepted concepts. It describes and/or models an application environment for interoperable geoprocessing and geospatial data and services products.
| Best Practices | A document containing discussion related to the use and/or implementation of an adopted OGC document. Best Practices Documents are an official position of the OGC and thus represent an endorsement of the content of the paper.
| Engineering Reports | Documents that are a primary output of OGC Interoperability Program Initiatives (testbeds, pilot projects and interoperability experiments). ERs represent consensus positions of the initiative participants and sponsors only. ERs become a publicly available document by consensus motion of the Standards Program. An ER does not represent the official position of the OGC nor of the OGC Technical Committee.
| Discussion Papers | A document containing discussion of some technology or standard area for release to the public. Discussion Papers are not the official position of the OGC and contain a statement to that effect.
| White Papers | A publication released by the OGC to the Public that states a position on a social, political, technical or other subject, often including a high-level explanation of an architecture or framework of a solution.

|===

OGC develops information models, usually in the form of XML Schema documents. The general process for disseminating a model is to publish a specification (or standard) document, and publish the XML schema to a schema repository. Based upon the status of the specification or documentation, the schemas will be posted to one of several http://www.ogcnetwork.net/schemarepos[OGC Schema repositories].

