
[appendix,obligation=informative]
== Revision history

[%unnumbered]
|===
^.^h| Date ^.^h| Version Doc. ^.^h| Editor ^.^h| Description

| 1996-05-09 | 0. | Kurt Buehler | OpenGIS Guide
| 2002-08-30 | 0.1 +
02-077 | Kurt Buehler | Initial version of ORM. Doc OGC +
George Percivall, Sam Bacharach, Carl Reed, Cliff Kottman, Chuck Heazel, John Davidson, Yaser Bisher, Harry Niedzwiadek, John Evans, Jeffrey Simon
| 2003-09-16 | 0.1.3 +
03-040 | George Percivall | Approved and published in public OGC baseline
| 2007 | (1.0) | | Unpublished HTML version http://ormdev.opengeospatial.org/ +
Contributors: Chuck Heazel, Carl Reed, Ron Fresne, Phillip Dibner, Josh Lieberman, John
Davidson, Lew Leinenweber, Raj Singh 
| 2008-11-11 | 2.0 +
08-062r4 | George Percivall | Approved by OAB and published in public OGC baseline +
Contributors: Carl Reed, Lew Leinenweber, Chris Tucker, Tina Cary
| 2011-10-13 | 2.1 (draft) +
08-062r5 | George Percivall | Final draft of version 2.1 including all changes to the OGC Baseline since version 2.0.
| 2011-12-15 | 2.1 +
08-062r7 | George Percivall | Implemented comments by the OGC Architecture Board (OAB) members including: F. Houbie, M. Botts, A. Matheus, J. Herring. +
Approved by OAB for release.

|===




[quote, "Jerome K Jerome, 1886"]
We are so bound together that no man can labor for himself alone. Each blow he strikes in his own behalf helps to mold the Universe.

[quote, "William James, 1890"]
Wisdom is knowing what to leave out
