== Conventions

This section provides details and examples for any conventions used in the document. Examples of conventions are symbols, abbreviations, use of XML schema, or special notes regarding how to read the document.

=== Identifiers

The normative provisions in this specification are denoted by the URI

http://www.opengis.net/spec/dggs/1.0[http://www.opengis.net/spec/dggs/1.0]

All requirements and conformance tests that appear in this document are denoted by partial URIs which are relative to this base.

=== UML notation

All the diagrams that appear in this specification are presented using the Unified Modeling Language (UML) static structure diagram, as described in Sub-clause 5.2 of OGC Web Service Common [OGC 06-121].

=== Abbreviated terms

CRS:: coordinate reference system

DE-9IM:: dimensionally extended nine-intersection model

DGGS:: discrete global grid system

ISO:: International Organization for Standardization

OGC:: Open Geospatial Consortium

OWS:: OGC Web Service

