
== Terms and Definitions

This document uses the terms defined in Sub-clause 5.3 of [OGC 06-121r9], which is based on the ISO/IEC Directives, Part 2, Rules for the structure and drafting of International Standards. In particular, the word “shall” (not “must”) is the verb form used to indicate a requirement to be strictly followed to conform to this standard.

=== dataset

collection of data, published or curated by a single agent, and available for access or download in one or more formats 

[.source]
<<dcat>>

NOTE: The use of 'collection' in the definition from <<dcat,[DCAT]>> is broader than the use of the term collection in this specification. See the definition of <<term-feature_collection,'feature collection'>>.

=== distribution

represents an accessible form of a *dataset* 

[.source]
<<dcat>>

[example]
a downloadable file, an RSS feed or an API.

=== feature

abstraction of real world phenomena [ISO 19101-1:2014]

NOTE: For those unfamiliar with the term 'feature', the explanations on https://www.w3.org/TR/sdw-bp/#spatial-things-features-and-geometry[Spatial Things, Features and Geometry] in the <<spatial_data_wbp,W3C/OGC Spatial Data on the Web Best Practice document>> provide more detail.

[[term-feature_collection]]
=== feature collection; collection

a set of *features* from a *dataset*

NOTE: In this specification, 'collection' is used as a synonym for 'feature collection'. This is done to make, for example, URI path expressions shorter and easier to understand for those that are not geo-experts.

=== Web API

API using an architectural style that is founded on the technologies of the Web 

[.source]
<<dwbp,DWBP>>

NOTE: https://www.w3.org/TR/dwbp/#APIHttpVerbs[Best Practice 24: Use Web Standards as the foundation of APIs] in the <<dwbp,W3C Data on the Web Best Practices>> provides more detail.

