
[[rc_core]]
== Requirements Class "Core"

[[overview]]
=== Overview 

[[core]]
[%unnumbered]
|===
2+h| Requirements Class
2+| http://www.opengis.net/spec/ogcapi-features-1/1.0/req/core
| Target type | Web API
| Dependency | <<rfc2616,RFC 2616 (HTTP/1.1)>>
| Dependency | <<rfc2818,RFC 2818 (HTTP over TLS)>>
| Dependency | <<rfc3339,RFC 3339 (Date and Time on the Internet: Timestamps)>>
| Dependency | <<rfc8288,RFC 8288 (Web Linking)>>
|===

A server that implements this conformance class provides access to the features in a https://www.w3.org/TR/vocab-dcat/#class-dataset[dataset]. In other words, the API is a https://www.w3.org/TR/vocab-dcat/#class-distribution[distribution] of that dataset. A file download, for example, would be another distribution.

NOTE: Other parts of this standard may define API extensions that support multiple datasets. The statement that the features are from "a dataset" is not meant to preclude such extensions. It just reflects that this document does not specify how the API publishes features or other spatial data from multiple datasets.

The entry point is a `Landing page` (path `/`).

NOTE: All paths (e.g., `/`) are relative to the base URL of the distribution of the dataset. If the API covers other resources beyond those specified in this document, the landing page may also be, for example, a sub-resource of the base URL of the API.

The `Landing page` provides links to:

* the `API definition` (link relations `service-desc` and `service-doc`),

* the `Conformance declaration` (path `/conformance`, link relation `conformance`), and

* the `Collections` (path `/collections`, link relation `data`).

The `API definition` describes the capabilities of the server that can be used by clients to connect to the server or by development tools to support the implementation of servers and clients. Accessing the `API definition` using HTTP GET returns a description of the API. The API definition can be hosted on the API server(s) or a separate server.

The `Conformance declaration` states the conformance classes from standards or community specifications, identified by a URI, that the API conforms to. Clients can but are not required to use this information. Accessing the `Conformance declaration` using HTTP GET returns the list of URIs of conformance classes implemented by the server.

The data is organized into one or more collections. `Collections` provides information about and access to the collections.

This document specifies requirements only for collections consisting of features. That is, each collection considered by this document is a feature collection. Other OGC API standards may add requirements for other types of collections.

NOTE: To support the future use of datasets with items that are not features, the term "feature" has not been added in the names of the resource types or their paths.

This standard does not include any requirements about how the features in the dataset have to be aggregated into collections. A typical approach is to aggregate by feature type but any other approach that fits the dataset or the applications using this distribution may also be used.

Accessing `Collections` using HTTP GET returns a response that contains at least the list of collections. For each `Collection`, a link to the items in the collection (`Features`, path `/collections/{collectionId}/items`, link relation `items`) as well as key information about the collection. This information includes:

* A local identifier for the collection that is unique for the dataset;

* A list of coordinate reference systems (CRS) in which geometries may be returned by the server: the first CRS is the default coordinate reference system (in the Core, the default is always WGS 84 with axis order longitude/latitude);

* An optional title and description for the collection;

* An optional extent that can be used to provide an indication of the spatial and temporal extent of the collection - typically derived from the data;

* An optional indicator about the type of the items in the collection (the default value, if the indicator is not provided, is 'feature').

The `Collection` resource is available at path `/collections/{collectionId}`, too, often with more details than included in the `Collections` response.

Each `Collection` that is a feature collection consists of features. This document only discusses the behavior of feature collections.

Each feature in a dataset is part of exactly one collection.

Accessing the `Features` using HTTP GET returns a document consisting of features in the collection. The features included in the response are determined by the server based on the query parameters of the request. To support access to larger collections without overloading the client, the API supports paged access with links to the next page, if more features are selected than the page size.

A `bbox` or `datetime` parameter may be used to select only a subset of the features in the collection (the features that are in the bounding box or time interval). The `bbox` parameter matches all features in the collection that are not associated with a location, too. The `datetime` parameter matches all features in the collection that are not associated with a time stamp or interval, too.

The `limit` parameter may be used to control the subset of the selected features that should be returned in the response, the page size.

Each page may include information about the number of selected and returned features (`numberMatched` and `numberReturned`) as well as links to support paging (link relation `next`).

Each `Feature` (path `/collections/{collectionId}/items/{featureId}`) is also a separate resource and may be requested individually using HTTP GET.

In addition to the simple path structures described above, where all features are organized in a one-level collection hierarchy, additional parts of the OGC API Feature series are expected to provide alternate access to the features served by the API via additional, deeper collection hierarchies.

[[api_landing_page]]
=== API landing page

==== Operation

[[req_core_root_op]]
[%unnumbered]
|=== 
^.^h| Requirement 1 h| /req/core/root-op
^.^| A | The server SHALL support the HTTP GET operation at the path `/`.
|=== 

==== Response

[[req_core_root_success]]
[%unnumbered]
|=== 
^.^h| Requirement 2 h| /req/core/root-success
^.^| A | A successful execution of the operation SHALL be reported as a response with a HTTP status code `200`.
^.^| B a| The content of that response SHALL be based upon the OpenAPI 3.0 schema http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/schemas/landingPage.yaml[landingPage.yaml] and include at least links to the following resources: +
- the API definition (relation type 'service-desc' or 'service-doc') +
- `/conformance` (relation type 'conformance') +
- `/collections` (relation type 'data') 
|=== 

http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/schemas/landingPage.yaml[Schema for the landing page]

[source,xml]
----
type: object
required:
  - links
properties:
  title:
    type: string
  description:
    type: string
  links:
    type: array
    items:
      $ref: http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/schemas/link.yaml
----

.Landing page response document
====
[source,json]
----
{ 
  "title": "Buildings in Bonn",
  "description": "Access to data about buildings in the city of Bonn via a Web API that conforms to the OGC API Features specification.",
  "links": [
    { "href": "http://data.example.org/",
      "rel": "self", "type": "application/json", "title": "this document" },
    { "href": "http://data.example.org/api",
      "rel": "service-desc", "type": "application/vnd.oai.openapi+json;version=3.0", "title": "the API definition" },
    { "href": "http://data.example.org/api.html",
      "rel": "service-doc", "type": "text/html", "title": "the API documentation" },
    { "href": "http://data.example.org/conformance",
      "rel": "conformance", "type": "application/json", "title": "OGC API conformance classes implemented by this server" },
    { "href": "http://data.example.org/collections",
      "rel": "data", "type": "application/json", "title": "Information about the feature collections" }
  ]
}
----
====

==== Error situations

See <<http_status_codes,HTTP status codes>> for general guidance.

=== API definition

==== Operation

Every API is expected to provide a definition that describes the capabilities of the server and which can be used by developers to understand the API, by software clients to connect to the server, or by development tools to support the implementation of servers and clients.

[[req_core_api_definition_op]]
[%unnumbered]
|=== 
^.^h| Requirement 3 h| /req/core/api-definition-op
^.^| A | The URIs of all API definitions referenced from the landing page SHALL support the HTTP GET method.
|=== 

[%unnumbered]
|=== 
^.^h| Permission 1 h| /per/core/api-definition-uri
^.^| A | The API definition is metadata about the API and strictly not part of the API itself, but it MAY be hosted as a sub-resource to the base path of the API, for example, at path `/api`. There is no need to include the path of the API definition in the API definition itself.
|=== 

Note that multiple API definition formats can be supported.

==== Response

[[req_core_api_definition_success]]
[%unnumbered]
|=== 
^.^h| Requirement 4 h| /req/core/api-definition-success
^.^| A | A GET request to the URI of an API definition linked from the landing page (link relations `service-desc` or `service-doc`) with an `Accept` header with the value of the link property `type` SHALL return a document consistent with the requested media type.
|=== 

[%unnumbered]
|=== 
^.^h| Recommendation 1 h| /rec/core/api-definition-oas
^.^| A | If the API definition document uses the OpenAPI Specification 3.0, the document SHOULD conform to the <<rc_oas30,OpenAPI Specification 3.0 requirements class>>.
|=== 

If the server hosts the API definition under the base path of the API (for example, at path `/api`, see above), there is no need to include the path of the API definition in the API definition itself.

The idea is that any OGC API Features implementation can be used by developers that are familiar with the API definition language(s) supported by the server. For example, if an OpenAPI definition is used, it should be possible to create a working client using the OpenAPI definition. The developer may need to learn a little bit about geometry data types, etc., but it should not be required to read this standard to access the data via the API.

In case the API definition is based on OpenAPI 3.0, consider the <<two_approaches_oas,two approaches>> discussed in OpenAPI requirements class.

==== Error situations

See <<http_status_codes,HTTP status codes>> for general guidance.

[[declaration_of_conformance_classes]]
=== Declaration of conformance classes

==== Operation

To support "generic" clients that want to access multiple OGC API Features implementations - and not "just" a specific API / server, the server has to declare the conformance classes it implements and conforms to.

[[req_core_conformance_op]]
[%unnumbered]
|=== 
^.^h| Requirement 5 h| /req/core/conformance-op
^.^| A | The server SHALL support the HTTP GET operation at the path `/conformance`.
|=== 

==== Response

[[req_core_conformance_success]]
[%unnumbered]
|=== 
^.^h| Requirement 6 h| /req/core/conformance-success
^.^| A | A successful execution of the operation SHALL be reported as a response with a HTTP status code `200`.
^.^| B | The content of that response SHALL be based upon the OpenAPI 3.0 schema http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/schemas/confClasses.yaml[confClasses.yaml] and list all OGC API conformance classes that the server conforms to.
|=== 

http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/schemas/confClasses.yaml[Schema for the list of conformance classes]

[source,xml]
----
type: object
required:
  - conformsTo
properties:
  conformsTo:
    type: array
    items:
      type: string
----

.Conformance declaration response document
====
This example response in JSON is for a server that supports OpenAPI 3.0 for the API definition and HTML and GeoJSON as encodings for features.

[source,json]
----
{
  "conformsTo": [
    "http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/core",
    "http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/oas30",
    "http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/html",
    "http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/geojson"
  ]
}
----
====


==== Error situations

See <<http_status_codes,HTTP status codes>> for general guidance.

[[http_1_1]]
=== HTTP 1.1

[[req_core_http]]
[%unnumbered]
|=== 
^.^h| Requirement 7 h| /req/core/http
^.^| A | The server SHALL conform to <<rfc2616,HTTP 1.1>>.
^.^| B | If the server supports HTTPS, the server SHALL also conform to <<rfc2818,HTTP over TLS>>.
|===

This includes the correct use of status codes, headers, etc.

[%unnumbered]
|=== 
^.^h| Recommendation 2 h| /rec/core/head
^.^| A | The server SHOULD support the HTTP 1.1 method HEAD for all resources that support the method GET.
|===

Supporting the method HEAD in addition to GET can be useful for clients and is simple to implement.

Servers implementing <<cross_origin,CORS>> will implement the method OPTIONS, too.

[[http_status_codes]]
==== HTTP status codes

This API standard does not impose any restrictions on which features of the HTTP and HTTPS protocols may be used. API clients should be prepared to handle any legal HTTP or HTTPS status code.

The *Status Codes* listed in <<table2>> are of particular relevance to implementors of this standard. Status codes 200, 400, and 404 are called out in API requirements. Therefore, support for these status codes is mandatory for all compliant implementations. The remainder of the status codes in <<table2>> are not mandatory, but are important for the implementation of a well functioning API. Support for these status codes is strongly encouraged for both client and server implementations.

[[table2]]
.Typical HTTP status codes
|===
h| Status code h| Description
| `200` | A successful request.
| `304` | An <<web_caching,entity tag was provided in the request>> and the resource has not been changed since the previous request.
| `400` | The server cannot or will not process the request due to an apparent client error. For example, a query parameter had an incorrect value.
| `401` | The request requires user authentication. The response includes a `WWW-Authenticate` header field containing a challenge applicable to the requested resource.
| `403` | The server understood the request, but is refusing to fulfill it. While status code `401` indicates missing or bad authentication, status code `403` indicates that authentication is not the issue, but the client is not authorized to perform the requested operation on the resource.
| `404` | The requested resource does not exist on the server. For example, a path parameter had an incorrect value.
| `405` | The request method is not supported. For example, a POST request was submitted, but the resource only supports GET requests.
| `406` | The `Accept` header submitted in the request did not support any of the media types supported by the server for the requested resource.
| `500` | An internal error occurred in the server.

|===

More specific guidance is provided for each resource, where applicable.

[%unnumbered]
|===
^.^h| Permission 2 h| /per/core/additional-status-codes
^.^| A | Servers MAY support other capabilities of the HTTP protocol and, therefore, MAY return other status codes than those listed in <<table2>>.

|===

The API Description Document describes the HTTP status codes generated by that API. This should not be an exhaustive list of all possible status codes. It is not reasonable to expect an API designer to control the use of HTTP status codes which are not generated by their software. Therefore, it is recommended that the API Description Document limit itself to describing HTTP status codes relevant to the proper operation of the API application logic. Client implementations should be prepared to receive HTTP status codes in addition to those described in the API Description Document.

=== Unknown or invalid query parameters

[[req_core_query_param_unknown]]
[%unnumbered]
|===
^.^h| Requirement 8 h| /req/core/query-param-unknown
^.^| A | The server SHALL respond with a response with the status code `400`, if the request URI includes a query parameter that is not specified in the API definition.

|===

If a server wants to support vendor specific parameters, these have to be explicitly declared in the API definition.

If OpenAPI is used to represent the API definition, a capability exists to allow additional parameters without explicitly declaring them. That is, parameters that have not been explicitly specified in the API definition for the operation will be ignored.

.OpenAPI schema for additional "free-form" query parameters
[source,xml]
----
in: query
name: vendorSpecificParameters
schema:
  type: object
  additionalProperties: true
style: form
----

Note that the name of the parameter does not matter as the actual query parameters are the names of the object properties. For example, assume that the value of `vendorSpecificParameters` is this object:

[source,json]
----
{
  "my_first_parameter": "some value",
  "my_other_parameter": 42
}
----

In the request URI this would be expressed as `&my_first_parameter=some%20value&my_other_parameter=42`.

[[req_core_query_param_invalid]]
[%unnumbered]
|===
^.^h| Requirement 9 h| /req/core/query-param-invalid
^.^| A | The server SHALL respond with a response with the status code `400`, if the request URI includes a query parameter that has an invalid value.
|===

This is a general rule that applies to all parameters, whether they are specified in this document or in additional parts. A value is invalid if it violates the API definition or any other constraint for that parameter stated in a requirement.

[[web_caching]]
=== Web caching

Entity tags are a mechanism for web cache validation and for supporting conditional requests to reduce network traffic. Entity tags are specified by <<rfc2616,HTTP/1.1 (RFC 2616)>>.

[%unnumbered]
|===
^.^h| Recommendation 3 h| /rec/core/etag
^.^| A | The service SHOULD support entity tags and the associated headers as specified by HTTP/1.1.
|===

[[cross_origin]]
=== Support for cross-origin requests

Access to data from a HTML page is by default prohibited for security reasons, if the data is located on another host than the webpage ("same-origin policy"). A typical example is a web-application accessing feature data from multiple distributed datasets.

[%unnumbered]
|===
^.^h| Recommendation 4 h| /rec/core/cross-origin
^.^| A | If the server is intended to be accessed from the browser, cross-origin requests SHOULD be supported. Note that support can also be added in a proxy layer on top of the server.
|===

Two common mechanisms to support cross-origin requests are:

* https://en.wikipedia.org/wiki/Cross-origin_resource_sharing[Cross-origin resource sharing (CORS)]; and

* https://en.wikipedia.org/wiki/JSONP[JSONP (JSON with padding)].

[[encodings]]
=== Encodings

While OGC API Features does not specify any mandatory encoding, support for the following encodings is recommended. See <<overview,Clause 6 (Overview)>> for a discussion.

[%unnumbered]
|===
^.^h| Recommendation 5 h| /rec/core/html
^.^| A | To support browsing the dataset and its features with a web browser and to enable search engines to crawl and index the dataset, implementations SHOULD consider to support an HTML encoding.
|===

[%unnumbered]
|===
^.^h| Recommendation 6 h| /rec/core/geojson
^.^| A | If the feature data can be represented for the intended use in GeoJSON, implementations SHOULD consider to support GeoJSON as an encoding for features and feature collections.
|===

<<http_1_1,Requirement `/req/core/http`>> implies that the encoding of a server response is determined using content negotiation as specified by the HTTP RFC.

The section <<media_types,Media Types>> includes guidance on media types for <<encodings,encodings>> that are specified in this document.

Note that any server that supports multiple encodings will have to support a mechanism to mint encoding-specific URIs for resources in order to express links, for example, to alternate representations of the same resource. This document does not mandate any particular approach how this is supported by the server.

As clients simply need to dereference the URI of the link, the implementation details and the mechanism how the encoding is included in the URI of the link are not important. Developers interested in the approach of a particular implementation, for example, to manipulate ("hack") URIs in the browser address bar, can study the API definition.

[NOTE]
====
Two common approaches are:

* an additional path for each encoding of each resource (this can be expressed, for example, using format specific suffixes like ".html");

* an additional query parameter (for example, "accept" or "f") that overrides the Accept header of the HTTP request.
====

=== String internationalization

If the server supports representing resources in multiple languages, the usual HTTP content negotiation mechanisms apply. The client states its language preferences in the `Accept-Language` header of a request and the server responds with responses that have linguistic text in the language that best matches the requested languages and the capabilities of the server.

[%unnumbered]
|===
^.^h| Recommendation 7 h| /rec/core/string-i18n
^.^| A | For encodings that support string internationalization, the server SHOULD include information about the language for each string value that includes linguistic text.
|===

For example, if JSON-LD is used as an encoding, the built-in capabilities to https://www.w3.org/TR/json-ld/#string-internationalization[annotate a string with its language] should be used.

The http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/schemas/link.yaml[link object] based on <<rfc8288,RFC 8288 (Web Linking)>> includes a `hreflang` attribute that can be used to state the language of the referenced resource. This can be used to include links to the same data in, for example, English or French. Just like with <<encodings,multiple encodings>> a server that wants to use language-specific links will have to support a mechanism to mint language-specific URIs for resources in order to express links to, for example, the same resource in another language. Again, this document does not mandate any particular approach how such a capability is supported by the server.

=== Coordinate reference systems

As discussed in Chapter 9 of the <<spatial_data_wbp,W3C/OGC Spatial Data on the Web Best Practices document>>, how to express and share the location of features in a consistent way is one of the most fundamental aspects of publishing geographic data and it is important to be clear about the coordinate reference system that coordinates are in.

For the reasons discussed in the Best Practices, OGC API Features uses WGS 84 longitude and latitude as the default coordinate reference system.

[[req_core_crs84]]
[%unnumbered]
|===
^.^h| Requirement 10 h| /req/core/crs84
^.^| A | Unless the client explicitly requests a different coordinate reference system, all spatial geometries SHALL be in the coordinate reference system http://www.opengis.net/def/crs/OGC/1.3/CRS84 (WGS 84 longitude/latitude) for geometries without height information and http://www.opengis.net/def/crs/OGC/0/CRS84h (WGS 84 longitude/latitude plus ellipsoidal height) for geometries with height information.
|===

Implementations compliant with the Core are not required to support publishing feature geometries in coordinate reference systems other than http://www.opengis.net/def/crs/OGC/1.3/CRS84 (for coordinates without height) or http://www.opengis.net/def/crs/OGC/0/CRS84h (for coordinates with height); i.e., the (optional) third coordinate number is always the height.

The Core also does not specify a capability to request feature geometries in a different coordinate reference system. Such a capability will be specified in another part of the OGC API Features series.

=== Link headers

[%unnumbered]
|===
^.^h| Recommendation 8 h| /rec/core/link-header
^.^| A a| Links included in payload of responses SHOULD also be included as `Link` headers in the HTTP response according to <<rfc8288,RFC 8288, Clause 3.>> +
This recommendation does not apply, if there are a large number of links included in a response or a link is not known when the HTTP headers of the response are created.
|===

[[feature_collections]]
=== Feature collections

==== Operation

[[req_core_fc_md_op]]
[%unnumbered]
|===
^.^h| Requirement 11 h| /req/core/fc-md-op
^.^| A | The server SHALL support the HTTP GET operation at the path `/collections`.
|===

==== Response

[[req_core_fc_md_success]]
[%unnumbered]
|===
^.^h| Requirement 12 h| /req/core/fc-md-success
^.^| A | A successful execution of the operation SHALL be reported as a response with a HTTP status code `200`.
^.^| B | The content of that response SHALL be based upon the OpenAPI 3.0 schema http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/schemas/collections.yaml[collections.yaml].
|===

http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/schemas/collections.yaml[Schema for the collections resource]

[source,xml]
----
type: object
required:
  - links
  - collections
properties:
  links:
    type: array
    items:
      $ref: http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/schemas/link.yaml
  collections:
    type: array
    items:
      $ref: http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/schemas/collection.yaml
----

[%unnumbered]
|===
^.^h| Requirement 13 h| /req/core/fc-md-links
^.^| A a| A `200`-response SHALL include the following links in the `links` property of the response: +
- a link to this response document (relation: `self`), +
- a link to the response document in every other media type supported by the server (relation: `alternate`).
^.^| B | All links SHALL include the `rel` and `type` link parameters.
|===

[%unnumbered]
|===
^.^h| Recommendation 9 h| /rec/core/fc-md-descriptions
^.^| A | If external schemas or descriptions for the dataset exist that provide information about the structure or semantics of the data, a `200`-response SHOULD include links to each of those resources in the `links` property of the response (relation: `describedBy`).
^.^| B | The `type` link parameter SHOULD be provided for each link. This applies to resources that describe to the whole dataset.
^.^| C | For resources that describe the contents of a feature collection, the links SHOULD be set in the `links` property of the appropriate object in the `collections` resource.
^.^| D | Examples for descriptions are: XML Schema, Schematron, JSON Schema, RDF Schema, OWL, SHACL, a feature catalogue, etc.
|===

[%unnumbered]
|===
^.^h| Recommendation 10 h| /rec/core/fc-md-license
^.^| A | For each feature collection in this distribution of the dataset, the `links` property of the collection SHOULD include an item for each supported encoding with a link to the collection resource (relation: `license`).
^.^| B | Alternatively, if all data shared via the API is available under the same license, the link MAY instead be added to the top-level `links` property of the response.
^.^| C | Multiple links to the license in different content types MAY be provided. At least a link to content type `text/html` or `text/plain` SHOULD be provided.
|===

[%unnumbered]
|===
^.^h| Requirement 14 h| /req/core/fc-md-items
^.^| A | For each feature collection provided by the server, an item SHALL be provided in the property `collections`.
|===

[%unnumbered]
|===
^.^h| Permission 3 h| /per/core/fc-md-items
^.^| A | To support servers with many collections, servers MAY limit the number of items in the property `collections`.
|===

This document does not specify mechanisms how clients may access all collections from servers with many collections. Such mechanisms may be specified in additional parts of OGC API Features. Options include support for paging and/or filtering.

[%unnumbered]
|===
^.^h| Requirement 15 h| /req/core/fc-md-items-links
^.^| A | For each feature collection included in the response, the `links` property of the collection SHALL include an item for each supported encoding with a link to the features resource (relation: `items`).
^.^| B | All links SHALL include the `rel` and `type` properties.
|===

[%unnumbered]
|===
^.^h| Requirement 16 h| /req/core/fc-md-extent
^.^| A | For each feature collection, the `extent` property, if provided, SHALL provide bounding boxes that include all spatial geometries and time intervals that include all temporal geometries in this collection. The temporal extent may use `null` values to indicate an open time interval.
^.^| B | If a feature has multiple properties with spatial or temporal information, it is the decision of the server whether only a single spatial or temporal geometry property is used to determine the extent or all relevant geometries.
|===

[%unnumbered]
|===
^.^h| Recommendation 11 h| /rec/core/fc-md-extent-single
^.^| A | While the spatial and temporal extents support multiple bounding boxes (`bbox` array) and time intervals (`interval` array) for advanced use cases, implementations SHOULD provide only a single bounding box or time interval unless the use of multiple values is important for the use of the dataset and agents using the API are known to be support multiple bounding boxes or time intervals.
|===

[%unnumbered]
|===
^.^h| Permission 4 h| /per/core/fc-md-extent-extensions
^.^| A | The Core only specifies requirements for spatial and temporal extents. However, the `extent` object MAY be extended with additional members to represent other extents, for example, thermal or pressure ranges.
^.^| B | The Core only supports spatial extents in WGS 84 longitude/latitude and temporal extents in the Gregorian calendar (these are the only enum values in http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/schemas/extent.yaml[extent.yaml]).
^.^| C | Extension to the Core MAY add additional reference systems to the `extent` object.
|===

http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/schemas/collection.yaml[Schema for a feature collection]

[source,xml]
----
type: object
required:
  - id
  - links
properties:
  id:
    description: identifier of the collection used, for example, in URIs
    type: string
  title:
    description: human readable title of the collection
    type: string
  description:
    description: a description of the features in the collection
    type: string
  links:
    type: array
    items:
      $ref: http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/schemas/link.yaml
  extent:
    description: >-
      The extent of the features in the collection. In the Core only spatial and temporal
      extents are specified. Extensions may add additional members to represent other
      extents, for example, thermal or pressure ranges.
    type: object
    properties:
      spatial:
        description: >-
          The spatial extent of the features in the collection.
        type: object
        properties:
          bbox:
            description: >-
              One or more bounding boxes that describe the spatial extent of the dataset.
              In the Core only a single bounding box is supported. Extensions may support
              additional areas. If multiple areas are provided, the union of the bounding
              boxes describes the spatial extent.
            type: array
            minItems: 1
            items:
              description: >-
                Each bounding box is provided as four or six numbers, depending on
                whether the coordinate reference system includes a vertical axis
                (height or depth):

                * Lower left corner, coordinate axis 1
                * Lower left corner, coordinate axis 2
                * Minimum value, coordinate axis 3 (optional)
                * Upper right corner, coordinate axis 1
                * Upper right corner, coordinate axis 2
                * Maximum value, coordinate axis 3 (optional)

                The coordinate reference system of the values is WGS 84 longitude/latitude
                (http://www.opengis.net/def/crs/OGC/1.3/CRS84) unless a different coordinate
                reference system is specified in `crs`.

                For WGS 84 longitude/latitude the values are in most cases the sequence of
                minimum longitude, minimum latitude, maximum longitude and maximum latitude.
                However, in cases where the box spans the antimeridian the first value
                (west-most box edge) is larger than the third value (east-most box edge).

                If the vertical axis is included, the third and the sixth number are
                the bottom and the top of the 3-dimensional bounding box.

                If a feature has multiple spatial geometry properties, it is the decision of the
                server whether only a single spatial geometry property is used to determine
                the extent or all relevant geometries.
              type: array
              minItems: 4
              maxItems: 6
              items:
                type: number
              example:
                - -180
                - -90
                - 180
                - 90
          crs:
            description: >-
              Coordinate reference system of the coordinates in the spatial extent
              (property `bbox`). The default reference system is WGS 84 longitude/latitude.
              In the Core this is the only supported coordinate reference system.
              Extensions may support additional coordinate reference systems and add
              additional enum values.
            type: string
            enum:
              - 'http://www.opengis.net/def/crs/OGC/1.3/CRS84'
            default: 'http://www.opengis.net/def/crs/OGC/1.3/CRS84'
      temporal:
        description: >-
          The temporal extent of the features in the collection.
        type: object
        properties:
          interval:
            description: >-
              One or more time intervals that describe the temporal extent of the dataset.
              The value `null` is supported and indicates an open time intervall.
              In the Core only a single time interval is supported. Extensions may support
              multiple intervals. If multiple intervals are provided, the union of the
              intervals describes the temporal extent.
            type: array
            minItems: 1
            items:
              description: >-
                Begin and end times of the time interval. The timestamps
                are in the coordinate reference system specified in `trs`. By default
                this is the Gregorian calendar.
              type: array
              minItems: 2
              maxItems: 2
              items:
                type: string
                format: date-time
                nullable: true
              example:
                - '2011-11-11T12:22:11Z'
                - null
          trs:
            description: >-
              Coordinate reference system of the coordinates in the temporal extent
              (property `interval`). The default reference system is the Gregorian calendar.
              In the Core this is the only supported temporal reference system.
              Extensions may support additional temporal reference systems and add
              additional enum values.
            type: string
            enum:
              - 'http://www.opengis.net/def/uom/ISO-8601/0/Gregorian'
            default: 'http://www.opengis.net/def/uom/ISO-8601/0/Gregorian'
  itemType:
    description: indicator about the type of the items in the collection (the default value is 'feature').
    type: string
    default: feature
  crs:
    description: the list of coordinate reference systems supported by the service
    type: array
    items:
      type: string
    default:
      - http://www.opengis.net/def/crs/OGC/1.3/CRS84
----

NOTE: The `crs` property of the `collection` object is not used by this conformance class, but reserved for future use.

.Feature collections response document
====
This feature collections example response in JSON is for a dataset with a single collection "buildings". It includes links to the features resource in all formats that are supported by the service (https://www.iana.org/assignments/link-relations/link-relations.xhtml[link relation type]: "items").

Representations of the resource in other formats are referenced using https://www.iana.org/assignments/link-relations/link-relations.xhtml[link relation type] "alternate".

An additional link is to a GML application schema for the dataset - using https://www.iana.org/assignments/link-relations/link-relations.xhtml[link relation type] "describedBy".

Finally there are also links to the license information for the building data (using https://www.iana.org/assignments/link-relations/link-relations.xhtml[link relation type] "license").

Reference system information is not provided as the service provides geometries only in the default systems (spatial: WGS 84 longitude/latitude; temporal: Gregorian calendar).

[source,json]
----
{
  "links": [
    { "href": "http://data.example.org/collections.json",
      "rel": "self", "type": "application/json", "title": "this document" },
    { "href": "http://data.example.org/collections.html",
      "rel": "alternate", "type": "text/html", "title": "this document as HTML" },
    { "href": "http://schemas.example.org/1.0/buildings.xsd",
      "rel": "describedBy", "type": "application/xml", "title": "GML application schema for Acme Corporation building data" },
    { "href": "http://download.example.org/buildings.gpkg",
      "rel": "enclosure", "type": "application/geopackage+sqlite3", "title": "Bulk download (GeoPackage)", "length": 472546 }
  ],
  "collections": [
    {
      "id": "buildings",
      "title": "Buildings",
      "description": "Buildings in the city of Bonn.",
      "extent": {
        "spatial": {
          "bbox": [ [ 7.01, 50.63, 7.22, 50.78 ] ]
        },
        "temporal": {
          "interval": [ [ "2010-02-15T12:34:56Z", null ] ]
        }
      },
      "links": [
        { "href": "http://data.example.org/collections/buildings/items",
          "rel": "items", "type": "application/geo+json",
          "title": "Buildings" },
        { "href": "https://creativecommons.org/publicdomain/zero/1.0/",
          "rel": "license", "type": "text/html",
          "title": "CC0-1.0" },
        { "href": "https://creativecommons.org/publicdomain/zero/1.0/rdf",
          "rel": "license", "type": "application/rdf+xml",
          "title": "CC0-1.0" }
      ]
    }
  ]
}
----

====

==== Error situations

See <<http_status_codes,HTTP status codes>> for general guidance.

[[feature_collection]]
=== Feature collection

==== Operation

[[req_core_sfc_md_op]]
[%unnumbered]
|===
^.^h| Requirement 17 h| /req/core/sfc-md-op
^.^| A | The server SHALL support the HTTP GET operation at the path `/collections/{collectionId}`.
^.^| B | The parameter `collectionId` is each `id` property in the feature collections response (JSONPath: `$.collections[*].id`).
|===

==== Response

[[req_core_sfc_md_success]]
[%unnumbered]
|===
^.^h| Requirement 18 h| /req/core/sfc-md-success
^.^| A | A successful execution of the operation SHALL be reported as a response with a HTTP status code `200`.
^.^| B | The content of that response SHALL be consistent with the content for this feature collection in the `/collections` response. That is, the values for `id`, `title`, `description` and `extent` SHALL be identical.
|===

==== Error situations

See <<http_status_codes,HTTP status codes>> for general guidance.

If the parameter `collectionId` does not exist on the server, the status code of the response will be `404` (see <<table2>>).

[[features]]
=== Features

==== Operation

[[req_core_fc_op]]
[%unnumbered]
|===
^.^h| Requirement 19 h| /req/core/fc-op
^.^| A | For every feature collection identified in the feature collections response (path `/collections`), the server SHALL support the HTTP GET operation at the path `/collections/{collectionId}/items`.
^.^| B | The parameter `collectionId` is each `id` property in the feature collections response (JSONPath: `$.collections[*].id`).
|===

==== Parameter limit

[[req_core_fc_limit_definition]]
[%unnumbered]
|===
^.^h| Requirement 20 h| /req/core/fc-limit-definition
^.^| A a| The operation SHALL support a parameter `limit` with the following characteristics (using an OpenAPI Specification 3.0 fragment): +
[source,xml]
----
name: limit
in: query
required: false
schema:
  type: integer
  minimum: 1
  maximum: 10000
  default: 10
style: form
explode: false
----
|===

[%unnumbered]
|===
^.^h| Permission 5 h| /per/core/fc-limit-default-minimum-maximum
^.^| A | The values for `minimum`, `maximum` and `default` in requirement `/req/core/fc-limit-definition` are only examples and MAY be changed.
|===

[[req_core_fc_limit_response]]
[%unnumbered]
|===
^.^h| Requirement 21 h| /req/core/fc-limit-response-1
^.^| A | The response SHALL not contain more features than specified by the optional `limit` parameter. If the API definition specifies a maximum value for `limit` parameter, the response SHALL not contain more features than this maximum value.
^.^| B | Only items are counted that are on the first level of the collection. Any nested objects contained within the explicitly requested items SHALL not be counted.
|===

[%unnumbered]
|===
^.^h| Permission 6 h| /per/core/fc-limit-response-2
^.^| A | The server MAY return less features than requested (but not more).
|===

A template for the definition of the parameter in YAML according to OpenAPI 3.0 is available at http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/parameters/limit.yaml[limit.yaml].

==== Parameter bbox

[[req_core_fc_bbox_definition]]
[%unnumbered]
|===
^.^h| Requirement 22 h| /req/core/fc-bbox-definition
^.^| A a| The operation SHALL support a parameter `bbox` with the following characteristics (using an OpenAPI Specification 3.0 fragment): +
[source,xml]
----
name: bbox
in: query
required: false
schema:
  type: array
  minItems: 4
  maxItems: 6
  items:
    type: number
style: form
explode: false
----
|===

[[req_core_fc_bbox_response]]
[%unnumbered]
|===
^.^h| Requirement 23 h| /req/core/fc-bbox-response
^.^| A | Only features that have a spatial geometry that intersects the bounding box SHALL be part of the result set, if the `bbox` parameter is provided.
^.^| B | If a feature has multiple spatial geometry properties, it is the decision of the server whether only a single spatial geometry property is used to determine the extent or all relevant geometries.
^.^| C | The `bbox` parameter SHALL match all features in the collection that are not associated with a spatial geometry, too.
^.^| D a| The bounding box is provided as four or six numbers, depending on whether the coordinate reference system includes a vertical axis (height or depth): +
- Lower left corner, coordinate axis 1 +
- Lower left corner, coordinate axis 2 +
- Minimum value, coordinate axis 3 (optional) +
- Upper right corner, coordinate axis 1 +
- Upper right corner, coordinate axis 2 +
- Maximum value, coordinate axis 3 (optional)
^.^| E | The bounding box SHALL consist of four numbers and the coordinate reference system of the values SHALL be interpreted as WGS 84 longitude/latitude (http://www.opengis.net/def/crs/OGC/1.3/CRS84) unless a different coordinate reference system is specified in a parameter `bbox-crs`.
^.^| F | The coordinate values SHALL be within the extent specified for the coordinate reference system.
|===

"Intersects" means that the rectangular area specified in the parameter `bbox` includes a coordinate that is part of the (spatial) geometry of the feature. This includes the boundaries of the geometries (e.g., for curves the start and end position and for surfaces the outer and inner rings).

This standard does not specify requirements for the parameter `bbox-crs`. Those requirements will be specified in an additional part of the OGC API Features series.

For WGS 84 longitude/latitude the bounding box is in most cases the sequence of minimum longitude, minimum latitude, maximum longitude and maximum latitude. However, in cases where the box spans the anti-meridian the first value (west-most box edge) is larger than the third value (east-most box edge).

.The bounding box of the New Zealand Exclusive Economic Zone
====
The bounding box of the New Zealand Exclusive Economic Zone in WGS 84 (from 160.6째E to 170째W and from 55.95째S to 25.89째S) would be represented in JSON as `[ 160.6, -55.95, -170, -25.89 ]` and in a query as `bbox=160.6,-55.95,-170,-25.89`.
====

Note that according to the requirement to <<query_param_invalid,return an error for an invalid parameter value>>, the server will return an error, if a latitude value of `160.0` is used.

If the vertical axis is included, the third and the sixth number are the bottom and the top of the 3-dimensional bounding box.

A template for the definition of the parameter in YAML according to OpenAPI 3.0 is available at http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/parameters/bbox.yaml[bbox.yaml].


==== Parameter datetime

[[req_core_fc_time_definition]]
[%unnumbered]
|===
^.^h| Requirement 24 h| /req/core/fc-time-definition
^.^| A a| The operation SHALL support a parameter `datetime` with the following characteristics (using an OpenAPI Specification 3.0 fragment): +
[source,xml]
----
name: datetime
in: query
required: false
schema:
  type: string
style: form
explode: false
----
|===

[[req_core_fc_time_response]]
[%unnumbered]
|===
^.^h| Requirement 25 h| /req/core/fc-time-response
^.^| A | Only features that have a temporal geometry that intersects the temporal information in the `datetime` parameter SHALL be part of the result set, if the parameter is provided.
^.^| B | If a feature has multiple temporal properties, it is the decision of the server whether only a single temporal property is used to determine the extent or all relevant temporal properties.
^.^| C | The `datetime` parameter SHALL match all features in the collection that are not associated with a temporal geometry, too.
^.^| D a| Temporal geometries are either a date-time value or a time interval. The parameter value SHALL conform to the following syntax (using https://tools.ietf.org/html/rfc2234[ABNF]): +
[source,xml]
----
interval-closed     = date-time "/" date-time
interval-open-start = [".."] "/" date-time
interval-open-end   = date-time "/" [".."]
interval            = interval-closed / interval-open-start / interval-open-end
datetime            = date-time / interval
----
^.^| E | The syntax of `date-time` is specified by https://tools.ietf.org/html/rfc3339#section-5.6[RFC 3339, 5.6].
^.^| F | Open ranges in time intervals at the start or end are supported using a double-dot (`..`) or an empty string for the start/end.
|===

"Intersects" means that the time (instant or interval) specified in the parameter `datetime` includes a timestamp that is part of the temporal geometry of the feature (again, a time instant or interval). For time intervals this includes the start and end time.

NOTE: ISO 8601-2 distinguishes open start/end timestamps (double-dot) and unknown start/end timestamps (empty string). For queries, an unknown start/end has the same effect as an open start/end.

.A date-time 
====
February 12, 2018, 23:20:52 UTC:

`datetime=2018-02-12T23%3A20%3A52Z`
====

For features with a temporal property that is a timestamp (like `lastUpdate` in the building features), a date-time value would match all features where the temporal property is identical.

For features with a temporal property that is a date or a time interval, a date-time value would match all features where the timestamp is on that day or within the time interval.

.Intervals
====
February 12, 2018, 00:00:00 UTC to March 18, 2018, 12:31:12 UTC:

`datetime=2018-02-12T00%3A00%3A00Z%2F2018-03-18T12%3A31%3A12Z`

February 12, 2018, 00:00:00 UTC or later:

`datetime=2018-02-12T00%3A00%3A00Z%2F.. or datetime=2018-02-12T00%3A00%3A00Z%2F`

March 18, 2018, 12:31:12 UTC or earlier:

`datetime=..%2F2018-03-18T12%3A31%3A12Z or datetime=%2F2018-03-18T12%3A31%3A12Z`
====

For features with a temporal property that is a timestamp (like `lastUpdate` in the building features), a time interval would match all features where the temporal property is within the interval.

For features with a temporal property that is a date or a time interval, a time interval would match all features where the values overlap.

A template for the definition of the parameter in YAML according to OpenAPI 3.0 is available at http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/parameters/datetime.yaml[datetime.yaml].

==== Parameters for filtering on feature properties

[%unnumbered]
|===
^.^h| Recommendation 12 h| /rec/core/fc-filters
^.^| A a| If features in the feature collection include a feature property that has a simple value (for example, a string or integer) that is expected to be useful for applications using the service to filter the features of the collection based on this property, a parameter with the name of the feature property and with the following characteristics (using an OpenAPI Specification 3.0 fragment) SHOULD be supported: +
[source,xml]
----
in: query
required: false
style: form
explode: false
----

The `schema` property SHOULD be the same as the definition of the feature property in the response schema.

|=== 

.An additional parameter to filter buildings based on their function
====
[source,xml]
----
name: function
in: query
description: >-
  Only return buildings of a particular function.\

  Default = return all buildings.
required: false
schema:
  type: string
  enum:
    - residential
    - commercial
    - public use
style: form
explode: false
example: 'function=public+use'
----
====

.An additional parameter to filter buildings based on their name
====
[source,xml]
----
name: name
in: query
description: >-
  Only return buildings with a particular name. Use '*' as a wildcard.\

  Default = return all buildings.
required: false
schema:
  type: string
style: form
explode: false
example: 'name=A*'
----

For string-valued properties, servers could support wildcard searches. The example included in the OpenAPI fragment would search for all buildings with a name that starts with "A."
====

==== Combinations of filter parameters

Any combination of `bbox`, `datetime` and parameters for filtering on feature properties is allowed. Note that the requirements on these parameters imply that only features matching all the predicates are in the result set; i.e., the logical operator between the predicates is 'AND.'

==== Response

[[req_core_fc_response]]
[%unnumbered]
|===
^.^h| Requirement 26 h| /req/core/fc-response
^.^| A | A successful execution of the operation SHALL be reported as a response with a HTTP status code `200`.
^.^| B | The response SHALL only include features selected by the request.
|===

The number of features returned depends on the server and the parameter `limit`.

* The client can request a limit it is interested in.

* The server likely has a default value for the limit, and a maximum limit.

* If the server has any more results available than it returns (the number it returns is less than or equal to the requested/default/maximum limit) then the server will include a link to the next set of results.

So (using the default/maximum values of 10/10000 from the OpenAPI fragment in requirement `/req/core/fc-limit-definition`):

* If you ask for 10, you will get 0 to 10 (as requested) and if there are more, a `next` link;

* If you dont specify a limit, you will get 0 to 10 (default) and if there are more, a `next` link;

* If you ask for 50000, you might get up to 10000 (server-limited) and if there are more, a `next` link;

* If you follow the next link from the previous response, you might get up to 10000 additional features and if there are more, a `next` link.

[[req_core_fc_links]]
[%unnumbered]
|===
^.^h| Requirement 27 h| /req/core/fc-links
^.^| A a| A `200`-response SHALL include the following links: +
- a link to this response document (relation: `self`), +
- a link to the response document in every other media type supported by the service (relation: `alternate`).
|=== 

[%unnumbered]
|===
^.^h| Recommendation 13 h| /rec/core/fc-next-1
^.^| A | A `200`-response SHOULD include a link to the next "page" (relation: `next`), if more features have been selected than returned in the response.
|=== 

[%unnumbered]
|===
^.^h| Recommendation 14 h| /rec/core/fc-next-2
^.^| A | Dereferencing a `next` link SHOULD return additional features from the set of selected features that have not yet been returned.
|=== 

[%unnumbered]
|===
^.^h| Recommendation 15 h| /rec/core/fc-next-3
^.^| A | The number of features in a response to a `next` link SHOULD follow the same rules as for the response to the original query and again include a `next` link, if there are more features in the selection that have not yet been returned.
|=== 

This document does not mandate any specific implementation approach for the `next` links.

An implementation could use opaque links that are managed by the server. It is up to the server to determine how long these links can be de-referenced. Clients should be prepared to receive a 404 response.

Another implementation approach is to use an implementation-specific parameter that specifies the index within the result set from which the server begins presenting results in the response, like the `startIndex` parameter that was used in <<wfs20,WFS 2.0>> (and which may be added again in additional parts of the OGC API Features series).

Clients should not assume that paging is safe against changes to dataset while a client iterates through `next` links. If a server provides opaque links these could be safe and maintain the dataset state during the original request. Using a parameter for the start index, however, will not be safe.

NOTE: Additional conformance classes for safe paging or an index parameter may be added in extensions to this specification.

[%unnumbered]
|===
^.^h| Permission 7 h| /per/core/fc-prev
^.^| A | A response to a `next` link MAY include a `prev` link to the resource that included the `next` link.
|=== 

Providing `prev` links supports navigating back and forth between pages, but depending on the implementation approach it may be too complex to implement.

[[req_core_fc_rel_type]]
[%unnumbered]
|===
^.^h| Requirement 28 h| /req/core/fc-rel-type
^.^| A | All links SHALL include the `rel` and `type` link parameters.
|=== 

[[req_core_fc_timestamp]]
[%unnumbered]
|===
^.^h| Requirement 29 h| /req/core/fc-timeStamp
^.^| A | If a property `timeStamp` is included in the response, the value SHALL be set to the time stamp when the response was generated.
|=== 

[[req_core_fc_numbermatched]]
[%unnumbered]
|===
^.^h| Requirement 30 h| /req/core/fc-numberMatched
^.^| A | If a property `numberMatched` is included in the response, the value SHALL be identical to the number of features in the feature collections that match the selection parameters like `bbox`, `datetime` or additional filter parameters.
^.^| B | A server MAY omit this information in a response, if the information about the number of matching features is not known or difficult to compute.
|=== 

[[req_core_fc_numberreturned]]
[%unnumbered]
|===
^.^h| Requirement 31 h| /req/core/fc-numberReturned
^.^| A | If a property `numberReturned` is included in the response, the value SHALL be identical to the number of features in the response.
^.^| B | A server MAY omit this information in a response, if the information about the number of features in the response is not known or difficult to compute.
|=== 

NOTE: The representation of the links and the other properties in the payload depends on the encoding of the feature collection.

.Links
====
If the request is to return building features and "10" is the default `limit`, the links in the response could be (in this example represented as link headers and using an additional parameter `offset` to implement `next` links - and the optional `prev` links):

[listing]
....
Link: <http://data.example.org/collections/buildings/items.json>; rel="self"; type="application/geo+json" +
Link: <http://data.example.org/collections/buildings/items.html>; rel="alternate"; type="text/html" +
Link: <http://data.example.org/collections/buildings/items.json?offset=10>; rel="next"; type="application/geo+json"
....

Following the `next` link could return:

[listing]
....
Link: <http://data.example.org/collections/buildings/items.json?offset=10>; rel="self"; type="application/geo+json" +
Link: <http://data.example.org/collections/buildings/items.html?offset=10>; rel="alternate"; type="text/html" +
Link: <http://data.example.org/collections/buildings/items.json?offset=0>; rel="prev"; type="application/geo+json" +
Link: <http://data.example.org/collections/buildings/items.json?offset=20>; rel="next"; type="application/geo+json"
....

If an explicit `limit` of "50" is used, the links in the response could be:

[listing]
....
Link: <http://data.example.org/collections/buildings/items.json?limit=50>; rel="self"; type="application/geo+json" +
Link: <http://data.example.org/collections/buildings/items.html?limit=50>; rel="alternate"; type="text/html" +
Link: <http://data.example.org/collections/buildings/items.json?limit=50&offset=50>; rel="next"; type="application/geo+json"
....

Following the `next` link could return:

[listing]
....
Link: <http://data.example.org/collections/buildings/items.json?limit=50&offset=50>; rel="self"; type="application/geo+json" +
Link: <http://data.example.org/collections/buildings/items.html?limit=50&offset=50>; rel="alternate"; type="text/html" +
Link: <http://data.example.org/collections/buildings/items.json?limit=50&offset=0>; rel="prev"; type="application/geo+json" +
Link: <http://data.example.org/collections/buildings/items.json?limit=50&offset=100>; rel="next"; type="application/geo+json"
....
====

==== Error situations

See <<http_status_codes,HTTP status codes>> for general guidance.

If the path parameter `collectionId` does not exist on the server, the status code of the response will be `404`.

A `400` will be returned in the following situations:

* If query parameter `limit` is not an integer or not between minimum and maximum;

* if query parameter `bbox` does not have 4 (or 6) numbers or they do not form a bounding box;

* if parameter `datetime` is not a valid time stamp or time interval.

[[feature]]
=== Feature

==== Operation

[[req_core_f_op]]
[%unnumbered]
|===
^.^h| Requirement 32 h| /req/core/f-op
^.^| A | For every feature in a feature collection (path `/collections/{collectionId}`), the server SHALL support the HTTP GET operation at the path `/collections/{collectionId}/items/{featureId}`.
^.^| B | The parameter `collectionId` is each `id` property in the feature collections response (JSONPath: `$.collections[*].id`). `featureId` is a local identifier of the feature.
|=== 

[%unnumbered]
|===
^.^h| Permission 8 h| /per/core/f-id
^.^| A | The Core requirements class only requires that the feature URI is unique. Implementations MAY apply stricter rules and, for example, use unique `id` values per dataset or collection.
|=== 

==== Response

[[req_core_f_success]]
[%unnumbered]
|===
^.^h| Requirement 33 h| /req/core/f-success
^.^| A | A successful execution of the operation SHALL be reported as a response with a HTTP status code `200`.
|=== 

[[req_core_f_links]]
[%unnumbered]
|===
^.^h| Requirement 34 h| /req/core/f-links
^.^| A a| A `200`-response SHALL include the following links in the response: +
- a link to the response document (relation: `self`), +
- a link to the response document in every other media type supported by the service (relation: `alternate`), and +
- a link to the feature collection that contains this feature (relation: `collection`).
^.^| B | All links SHALL include the `rel` and `type` link parameters.
|=== 

NOTE: The representation of the links in the payload will depend on the encoding of the feature.

.Links
====
The links in a feature could be (in this example represented as link headers):

[listing]
....
Link: <http://data.example.org/collections/buildings/items/123.json>; rel="self"; type="application/geo+json" +
Link: <http://data.example.org/collections/buildings/items/123.html>; rel="alternate"; type="text/html" +
Link: <http://data.example.org/collections/buildings.json>; rel="collection"; type="application/json" +
Link: <http://data.example.org/collections/buildings.html>; rel="collection"; type="text/html"
....
====

==== Error situations

See <<http_status_codes,HTTP status codes>> for general guidance.

If the path parameter `collectionId` or the path parameter `featureId` do not exist on the server, the status code of the response will be `404`.

