
== Terms and Definitions

This document uses the terms defined in Sub-clause 5.3 of OGC 06-121r8, which is based on the ISO/IEC Directives, Part 2, Rules for the structure and drafting of International Standards. In particular, the word "shall" (not "must") is the verb form used to indicate a requirement to be strictly followed to conform to this standard.

=== Moving feature

Representation, using a local origin and local ordinate *vectors*, of a *geometric object* at a given reference time.

[.source]
<<iso19141>>

=== Vector

Quantity having direction as well as magnitude.

[.source]
<<iso19123>>

=== Geometric object

Spatial object representing a geometric set.

[.source]
<<iso19107>>

=== Geometric primitive

*Geometric object* representing a single, connected, homogeneous element of space.

[.source]
<<iso19107>>

=== Period

1-dimensional *geometric primitive* representing extent in time.

[.source]
<<iso19141>>

=== Instant

0-dimensional *geometric primitive* representing a position in time.

[.source]
<<iso19141>>

=== Point

0-dimensional *geometric primitive* representing a position.

[.source]
<<iso19107>>

=== Trajectory

Path of a moving *point* described by a one parameter set of points.

[.source]
<<iso19141>>

=== Foliation

*One parameter set of geometries* such that each point in the *prism* of the set is in one and only one *trajectory* and in one and only one *leaf*.

[.source]
<<iso19141>>

=== One parameter set of geometries

Function _f_ from an interval _t_ ∈ [_a_, _b_] such that _f_(_t_) is a geometry and for each point _P_∈_f_(_a_) there is a one parameter set of points (called the trajectory of _P_) _P_(_t_) : [_a_, _b_] → _P_(_t_) such that _P_(_t_) ∈_f_(_t_).

[.source]
<<iso19141>>

=== Prism (one parameter set of geometries)

Set of points in the union of the geometries (or the union of the trajectories) of a one parameter set of geometries.

[.source]
<<iso19141>>

=== Leaf (one parameter set of geometries)

Geometry at a particular value of the parameter.

[.source]
<<iso19141>>

=== Dataset

An identifiable collection of data.

[.source]
<<iso19101>>.

=== Attribute

NetCDF attributes hold metadata. An attribute contains information about properties of a variable or an entire *dataset*.

[.source]
<<ogc10-090r3>>.

=== Global attribute

Global *attributes* apply to a whole *dataset* and may be used to record properties of all the data in a file, such as processing history or conventions used.

[.source]
<<ogc10-090r3>>

=== Variable attribute

Variable *attributes* record the properties of one *variable*.

[.source]
<<ogc10-090r3>>

=== Variable

A netCDF variable has a name, type, *shape*, *attributes*, and values. In face, much of the netCDF specification consists of defining the specific characteristics of variables. Variables hold data values. In the netCDF model, a variable can hold a multidimensional array of values of the same type.

[.source]
<<ogc10-090r3>>

=== Shape

The shape of a *variable* is specified with a list of zero or more *dimensions*.

[.source]
<<ogc10-090r3>>

=== Dimension

NetCDF dimensions are used to specify variable *shapes*, common grids, and coordinate systems.

[.source]
<<ogc10-090r3>>
