
== Common model
The following section covers aspects common to all WAMI services.

=== RESTful HTTP
The term RESTful HTTP is used to represent a stateless HTTP request/response model, a client and server processing one independent HTTP request at a time. WAMI services use a RESTful architecture.

==== HTTP request
The general model of the grammar is derived from OGC. All services support HTTP GET and POST. Details are in the main document and most readers familiar with OGC specification already know all of this in great detail. If a request is short (about 2KB), use GET; whereas a POST permits unbounded multi-valued input parameter sequences, i.e. really long requests.

A GET request is of the general form `http://host[:port]/path[?querystring]`. A `querystring` is a KVP footnote:[KVP – Key Value Pair or name-value pair such as `Version=1.0.2` or `Service=CS` or `Request=GetMap`] set of the form: `name=value[&name=value]`. Example: `http://example.com/IS?Service=IS&Version=1.0.2&Format=text/xml&Request=GetCapabilities`. A POST request: `http://host[:port]/path`. The body of a POST request contains the KVP or `name=value` pair encoding. For `name=value` pairs, name is not case sensitive and is of the form `part[.part]`. For example, `VERSION=1.0.2` and `Version=1.0.2` are valid and `name` can be `options.mpeg2.codec` or `Request`.

==== HTTP response
The layout of an HTTP response is standardized based on the request type. Exception reporting is drawn directly from OGC. Each request has a corresponding section on response schema in OGC 12-032r2.

=== Required parameters
As with OGC services, all WAMI requests require SERVICE, REQUEST and VERSION.

. SERVICE identifies a CS, IS, VS, RS, etc.E.g. `Service=CS`
. REQUEST identifies the operation to be performed. E.g. `Request=GetMap`
. VERSION identifies the WAMI specification version a client wants to use. E.g. `Version=1.0.2`

=== Common WAMI requests
*GetCapabilities* and *GetHelp* are common to all WAMI services. The mandatory *GetCapabilities* request informs a client about all the requests the server supports and how. *GetHelp* is optional and allows vendor to deliver customer support documentation. WAMI GetCapabilities for all services is summarized in <<annex-requests-summerized>>. See examples in <<annex-examples>>.
