name: publish

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup snaps
        run: |
          sudo snap install jq
          sudo snap install yq
      - uses: actions/checkout@master
      - name: Build document in the Metanorma container
        env:
          METANORMA_DOCKER: metanorma/metanorma:latest
        run: |
          make clean all publish
      - uses: actions/upload-artifact@master
        with:
          name: published
          path: published

  deploy-gh-pages:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@master
    - uses: actions/download-artifact@master
      with:
        name: published
    - name: deploy-to-gh
      env:
        GH_DEPLOY_KEY: ${{ secrets.GH_DEPLOY_KEY }}
        GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
      run: |
        curl -L https://raw.githubusercontent.com/metanorma/metanorma-build-scripts/master/ghactions-deploy-to-gh-pages.sh | bash
